#!/usr/bin/env python

"""
Parses the command line options using optparse.
"""

# Built-in modules #
import os, sys, optparse, inspect, subprocess

###############################################################################
# Special module location #
self_path = inspect.getfile(inspect.currentframe())
presumed_module_dir = os.path.abspath(os.path.dirname(self_path) + '/../')
sys.path.insert(0, presumed_module_dir)

# Required modules #
modules = ['illumitag', 'Bio', 'sh', 'patsy', 'pandas', 'statsmodels', 'fastqident']

# We might be missing some modules #
for module in modules:
    try:
        __import__(module)
    except ImportError as e:
        if str(e) != 'No module named %s' % module: raise e
        print 'You do not seem to have the "%s" package properly installed.' \
              ' Either you never installed it or your $PYTHON_PATH is not set up correctly.' \
              ' For more instructions see the README file. (%s)' % (module, e)
        sys.exit()

# Now we can have them #
import illumitag, sh
from illumitag.common import Color

# Where the module is #
module_dir = os.path.dirname(illumitag.__file__)
project_dir = os.path.abspath(module_dir + '/../')

# If the module is a git repository, get the hash #
if os.path.exists(project_dir + '/.git'):
    version = sh.git("--git-dir=" + project_dir + '/.git', "describe", "--tags", "--dirty", "--always").strip('\n')
else:
    version = illumitag.__version__

###############################################################################
# Required executables #
executables = ['blastall', 'pandaseq', 'mothur']

# We might be missing some executables #
def check_executable(tool_name):
    """Raises an exception if the executable *tool_name* is not found."""
    result = subprocess.call(['which', tool_name], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result != 0:
        message = "The executable '%s' cannot be found in your $PATH" % tool_name
        raise Exception(message)
for exe in executables: check_executable(exe)

###############################################################################
# The long description #
description = """
A python package.
An example usage is the following:
"$ illumitag pool1"
"""

# Options #
option_list = [
    optparse.make_option("-s", "--steps", type="string", help="Steps to run")
]

# All the help messages #
parameters = {
    'usage'   : '%prog POOL',
    'version' : illumitag.__version__,
    'epilog'  : 'Using version %s from %s' % (version, module_dir),
    'description' : description,
    'option_list' : option_list,
}

# Optparse is deprecated as of 2.7 #
parser = optparse.OptionParser(**parameters)
options, args = parser.parse_args()

# Check the positional arguments we got #
if len(args) < 1:
    parser.error("You need to specify a pool")

###############################################################################
# Everything is ok, start program #
print "Using version %s%s%s from %s" % (Color.b_grn, version, Color.end, module_dir)
sys.stdout.flush()

# Send the arguments we got #
directory = args[0]
if options.steps: ex = illumitag.run_exp(directory, options.steps)
else:             ex = illumitag.run_exp(directory)

# Report success #
print "Success: results are in '%s'" % os.path.abspath(ex.base_dir)